Squash_reservation_system/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#TEMPLATE URL!
app_name = 'basic_app'

urlpatterns=[
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^reservation/$', views.reservation, name='reservation'),
]

Squash_reservation_system/learning/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^logout/$',views.user_logout,name="logout"),
    url(r'special/',views.special,name="special"),
]

Squash_reservation_system/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
#from PIL import ImageField
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional
    portfolio_site = models.URLField(blank=True)

    #profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

class CourtEvent(models.Model):

    name = models.CharField('Event Name', max_length = 120)
    event_day = models.CharField('Event Date', max_length = 120)
    event_time = models.TimeField("Event Time")

    #def __str__(self):
    #    return {self.name, self.event_day, self.event_time}

Squash_reservation_system/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site',)
        #fields = ('portfolio_site','profile_pic')

Squash_reservation_system/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from basic_app.models import CourtEvent


# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse("You are logged in, nice!")

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',{'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'basic_app/login.html',{})

#def reservation(request):
#    return render(request, 'basic_app/reservation.html')

def reservation(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        selected_day = request.POST.get('selected_day')
        selected_time = request.POST.get('selected_time')

        event1 = CourtEvent(name = username, event_day = selected_day, event_time = selected_time)
        event1.save()
        return HttpResponseRedirect(reverse('index'))

    else:
        events_list = CourtEvent.objects.all()
        my_dict = {
        'events_list':events_list,
        }

        def give_me_wyros_records():
            return events_list.filter('name'=="Wyro")

        eight=events_list.filter(event_time="8:00")
        if eight == True:
            my_dict.update('eight',eight)

        nine = events_list.filter(event_time="9:00")
        if nine == True:
            my_dict.update('nine',nine)

        ten = events_list.filter(event_time="10:00")
        if ten == True:
            my_dict.update('ten',ten)

        eleven = events_list.filter(event_time="11:00")
        if eleven == True:
            my_dict.update('eleven',eleven)

        twelve = events_list.filter(event_time="12:00")
        if twelve == True:
            my_dict.update('twelve',twelve)

        thirteen = events_list.filter(event_time="13:00")
        if thirteen == True:
            my_dict.update('thirteen',thirteen)

        fourteen = events_list.filter(event_time="14:00")
        if fourteen == True:
            my_dict.update('fourteen',fourteen)

        fifteen = events_list.filter(event_time="15:00")
        if fifteen == True:
            my_dict.update('fifteen',fifteen)

        return render(request, 'basic_app/reservation.html',my_dict)

Squash_reservation_system/templates/basic_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Squash reservation system</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href={% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}>
	  <link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
    <link rel="stylesheet" href={% static "style.css" %}>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">SQUASHY</a></li>
            <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="nav-link" href="{% url 'basic_app:register' %}">Register</a></li>

            {% if user.is_authenticated %}
              <li><a class="nav-link" href="{% url 'basic_app:reservation' %}">Make reservation</a></li>
              <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
              <li><a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
            {% endif %}
          </ul>
    </nav>

  <div class="containter">
    {% block body_block %}
    {% endblock %}
  </div>

    <script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
  	<script src={% static "js/main.js" %}></script>
    <script src={% static "selectingtable.js" %}></script>

  </body>
</html>

Squash_reservation_system/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <div class="container">
    <h1>Welcome to squash reservation system!</h1>
  </div>
</div>

{% endblock %}

Squash_reservation_system/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>

  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>

</div>

{% endblock %}

Squash_reservation_system/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Registration!</h1>
      <h3>Fill out the form:</h3>

      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
      </form>

        {% endif %}
    </div>

</div>

{% endblock %}

Squash_reservation_system/templates/basic_app/reservation.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <div class="container">
    <h1>{{ user.username }}, here you can reserve a court!</h1>
  </div>
</div>

<div class="table100 ver2 m-b-110">
					<table data-vertable="ver2">
						<thead>
							<tr class="row100 head">
								<th class="column100 column1" data-column="column1"></th>
								<th class="column100 column2" data-column="column2">Monday</th>
								<th class="column100 column3" data-column="column3">Tuesday</th>
								<th class="column100 column4" data-column="column4">Wednesday</th>
								<th class="column100 column5" data-column="column5">Thursday</th>
								<th class="column100 column6" data-column="column6">Friday</th>
								<th class="column100 column7" data-column="column7">Saturday</th>
                <th class="column100 column8" data-column="column8">Sunday</th>
							</tr>
						</thead>
						<tbody>

							<tr class="row100 firsthour">
								<td class="column10 column1" data-column="column1">08:00 - 09:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 8 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 8 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 8 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 8 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 8 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 8 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 8 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 secondhour">
								<td class="column10 column1" data-column="column1">09:00 - 10:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 9 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 9 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 9 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 9 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 9 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 9 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 9 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 thirdhour">
								<td class="column10 column1" data-column="column1">10:00 - 11:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 10 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 10 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 10 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 10 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 10 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 10 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 10 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 fourthhour">
								<td class="column10 column1" data-column="column1">11:00 - 12:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 11 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 11 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 11 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 11 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 11 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 11 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 11 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 fifthhour">
								<td class="column10 column1" data-column="column1">12:00 - 13:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 12 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 12 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 12 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 12 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 12 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 12 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 12 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 sixthhour">
								<td class="column10 column1" data-column="column1">13:00 - 14:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 13 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 13 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 13 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 13 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 13 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 13 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 13 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 seventhhour">
								<td class="column10 column1" data-column="column1">14:00 - 15:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 14 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 14 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 14 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 14 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 14 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 14 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 14 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

							<tr class="row100 eighthour">
								<td class="column10 column1" data-column="column1">15:00 - 16:00</td>
								<td class="column100 column2 {% for eve in events_list %}{% if eve.event_day == "Monday" and eve.event_time.hour == 15 %} RESERVED {% endif %}{% endfor %}" data-column="column2"></td>
								<td class="column100 column3 {% for eve in events_list %}{% if eve.event_day == "Tuesday" and eve.event_time.hour == 15 %} RESERVED {% endif %}{% endfor %}" data-column="column3"></td>
								<td class="column100 column4 {% for eve in events_list %}{% if eve.event_day == "Wednesday" and eve.event_time.hour == 15 %}RESERVED{% endif %}{% endfor %}" data-column="column4"></td>
								<td class="column100 column5 {% for eve in events_list %}{% if eve.event_day == "Thursday" and eve.event_time.hour == 15 %}RESERVED{% endif %}{% endfor %}" data-column="column5"></td>
								<td class="column100 column6 {% for eve in events_list %}{% if eve.event_day == "Friday" and eve.event_time.hour == 15 %}RESERVED{% endif %}{% endfor %}" data-column="column6"></td>
								<td class="column100 column7 {% for eve in events_list %}{% if eve.event_day == "Saturday" and eve.event_time.hour == 15 %}RESERVED{% endif %}{% endfor %}" data-column="column7"></td>
								<td class="column100 column8 {% for eve in events_list %}{% if eve.event_day == "Sunday" and eve.event_time.hour == 15 %}RESERVED{% endif %}{% endfor %}" data-column="column8"></td>
							</tr>

						</tbody>
					</table>
          <div class="jumbotron">
            <div class="container">
              <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{ user.username }}">
                <label for="selected_day">Selected day:</label>
                <input type="text" name="selected_day" placeholder="Selected Day">
                <label for="selected_time">Selected time(reservation for one hour):</label>
                <input type="time" name="selected_time" placeholder="Selected Time">
                <input type="submit" value="Reserve">
              </form>
            </div>
          </div>

				</div>

{% endblock %}